; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "BlueStar"
#define MyAppVersion "1.4.1"
#define MyAppPublisher "BlueStar Devs"
#define MyAppURL "https://github.com/Coronitaa/BlueStar"
#define MyAppExeName "BlueStar.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{5E97D4B6-7E93-4B9C-A20D-D1F5B4E2B1A8}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} v{#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DisableProgramGroupPage=yes
; Language selection dialog
ShowLanguageDialog=yes
; Architecture
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
; Output
OutputDir=dist
OutputBaseFilename=BlueStar-v{#MyAppVersion}-Setup-win-x64
SetupIconFile=src\BlueStar.App\Assets\bluestar.ico
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
  SettingsFile: String;
  AppDataFile: String;
  SelectedLang: String;
  FileContent: AnsiString;
  ContentStr: String;
begin
  if CurStep = ssPostInstall then
  begin
    if ActiveLanguage = 'spanish' then
      SelectedLang := 'es'
    else
      SelectedLang := 'en';

    SettingsFile := ExpandConstant('{app}\settings.json');
    if FileExists(SettingsFile) then
    begin
      if LoadStringFromFile(SettingsFile, FileContent) then
      begin
        ContentStr := String(FileContent);
        StringChange(ContentStr, '"language": "en"', '"language": "' + SelectedLang + '"');
        StringChange(ContentStr, '"language": "es"', '"language": "' + SelectedLang + '"');
        SaveStringToFile(SettingsFile, AnsiString(ContentStr), False);
      end;
    end;

    AppDataFile := ExpandConstant('{userappdata}\BlueStar\settings.json');
    if not DirExists(ExpandConstant('{userappdata}\BlueStar')) then
      CreateDir(ExpandConstant('{userappdata}\BlueStar'));

    if FileExists(AppDataFile) then
    begin
      if LoadStringFromFile(AppDataFile, FileContent) then
      begin
        ContentStr := String(FileContent);
        StringChange(ContentStr, '"language": "en"', '"language": "' + SelectedLang + '"');
        StringChange(ContentStr, '"language": "es"', '"language": "' + SelectedLang + '"');
        SaveStringToFile(AppDataFile, AnsiString(ContentStr), False);
      end;
    end
    else if FileExists(SettingsFile) then
    begin
      FileCopy(SettingsFile, AppDataFile, False);
    end;
  end;
end;
